// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACsREyUQhmF1V0A_03GtO9hdm5kMMxtVE',
    appId: '1:943829176655:web:f03dff8d93669405d8753a',
    messagingSenderId: '943829176655',
    projectId: 'ytask-21426',
    authDomain: 'ytask-21426.firebaseapp.com',
    databaseURL: 'https://ytask-21426-default-rtdb.firebaseio.com',
    storageBucket: 'ytask-21426.firebasestorage.app',
    measurementId: 'G-CD833821VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHqO2eFazR3HWc4WqvgXf_dXYClfhWRM',
    appId: '1:943829176655:android:0fa8544983fcb61bd8753a',
    messagingSenderId: '943829176655',
    projectId: 'ytask-21426',
    databaseURL: 'https://ytask-21426-default-rtdb.firebaseio.com',
    storageBucket: 'ytask-21426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5XsC9-9bL6KKKePxio6pD9J7sRu9JPc',
    appId: '1:943829176655:ios:42ffea43cfee422cd8753a',
    messagingSenderId: '943829176655',
    projectId: 'ytask-21426',
    databaseURL: 'https://ytask-21426-default-rtdb.firebaseio.com',
    storageBucket: 'ytask-21426.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS5XsC9-9bL6KKKePxio6pD9J7sRu9JPc',
    appId: '1:943829176655:ios:42ffea43cfee422cd8753a',
    messagingSenderId: '943829176655',
    projectId: 'ytask-21426',
    databaseURL: 'https://ytask-21426-default-rtdb.firebaseio.com',
    storageBucket: 'ytask-21426.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACsREyUQhmF1V0A_03GtO9hdm5kMMxtVE',
    appId: '1:943829176655:web:1afedcbb40d2f288d8753a',
    messagingSenderId: '943829176655',
    projectId: 'ytask-21426',
    authDomain: 'ytask-21426.firebaseapp.com',
    databaseURL: 'https://ytask-21426-default-rtdb.firebaseio.com',
    storageBucket: 'ytask-21426.firebasestorage.app',
    measurementId: 'G-GL4XNH31RC',
  );
}
